# Generated by Django 3.2.9 on 2022-02-10 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20220209_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='profile',
            field=models.ManyToManyField(to='api.Profile'),
        ),
        migrations.AddField(
            model_name='manga',
            name='profile',
            field=models.ManyToManyField(to='api.Profile'),
        ),
        migrations.AddField(
            model_name='movie',
            name='profile',
            field=models.ManyToManyField(to='api.Profile'),
        ),
    ]
