# Generated by Django 3.2.9 on 2022-02-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220209_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
