# Generated by Django 3.2.9 on 2022-02-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_anime_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='api.Genre'),
        ),
    ]
