# Generated by Django 3.2.9 on 2022-02-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220210_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='animes', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Profile'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='api.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='api.Profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(blank=True, related_name='animes', to='api.Anime')),
                ('mangas', models.ManyToManyField(blank=True, related_name='mangas', to='api.Manga')),
                ('movies', models.ManyToManyField(blank=True, related_name='movies', to='api.Movie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
