# Generated by Django 3.2.9 on 2022-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_social_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='api.Profile'),
        ),
    ]
