# Generated by Django 3.2.9 on 2022-02-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220210_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='api.Profile'),
        ),
    ]
