# Generated by Django 3.2.9 on 2022-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_social_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='animes', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='animes',
            field=models.ManyToManyField(blank=True, related_name='animes', to='api.Anime'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='mangas',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='api.Manga'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='social',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='social',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='api.Profile'),
        ),
    ]
