# Generated by Django 3.2.9 on 2022-02-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_chapter_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
