# Generated by Django 3.2.9 on 2022-02-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_manga_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='movieview',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
        migrations.AddField(
            model_name='movieview',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
