# Generated by Django 3.2.9 on 2022-02-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220211_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieView',
            new_name='MovieStatus',
        ),
        migrations.RenameField(
            model_name='moviestatus',
            old_name='status',
            new_name='watched',
        ),
    ]
