# Generated by Django 3.2.9 on 2022-02-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220211_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviestatus',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_status', to='api.movie'),
        ),
        migrations.RemoveField(
            model_name='moviestatus',
            name='profile',
        ),
        migrations.AddField(
            model_name='moviestatus',
            name='profile',
            field=models.ManyToManyField(blank=True, related_name='movie_status', to='api.Profile'),
        ),
    ]
