# Generated by Django 3.2.9 on 2022-02-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220211_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviestatus',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviestatus',
            name='movie',
            field=models.ManyToManyField(related_name='movie_status', to='api.Movie'),
        ),
        migrations.RemoveField(
            model_name='moviestatus',
            name='profile',
        ),
        migrations.AddField(
            model_name='moviestatus',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movie_status', to='api.profile'),
            preserve_default=False,
        ),
    ]
