# Generated by Django 3.2.9 on 2022-02-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220211_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('animes', models.ManyToManyField(blank=True, related_name='animes', to='api.Anime')),
                ('mangas', models.ManyToManyField(blank=True, related_name='mangas', to='api.Manga')),
            ],
        ),
        migrations.RemoveField(
            model_name='moviestatus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_status',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='MovieStatus',
        ),
        migrations.AddField(
            model_name='status',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.Movie'),
        ),
        migrations.AddField(
            model_name='status',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
