# Generated by Django 3.2.9 on 2022-02-11 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220211_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.anime')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MangaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.manga')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MovieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
