# Generated by Django 3.2.9 on 2022-02-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220211_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes', models.ManyToManyField(blank=True, related_name='animes', to='api.Anime')),
                ('mangas', models.ManyToManyField(blank=True, related_name='mangas', to='api.Manga')),
                ('movies', models.ManyToManyField(blank=True, related_name='movies', to='api.Movie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='mangastatus',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='mangastatus',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='moviestatus',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviestatus',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AnimeStatus',
        ),
        migrations.DeleteModel(
            name='MangaStatus',
        ),
        migrations.DeleteModel(
            name='MovieStatus',
        ),
    ]
