# Generated by Django 3.2.9 on 2022-02-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220211_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
