# Generated by Django 3.2.9 on 2022-02-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='profiles',
        ),
    ]
