# Generated by Django 3.2.9 on 2022-02-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_profile_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animes',
            field=models.ManyToManyField(through='api.Status', to='api.Anime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mangas',
            field=models.ManyToManyField(through='api.Status', to='api.Manga'),
        ),
        migrations.AddField(
            model_name='status',
            name='anime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.anime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='manga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.manga'),
            preserve_default=False,
        ),
    ]
