# Generated by Django 3.2.9 on 2022-02-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220212_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='campo',
        ),
    ]
