# Generated by Django 3.2.9 on 2022-02-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220212_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.profile'),
        ),
    ]
