# Generated by Django 3.2.9 on 2022-02-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220212_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviestatus', to='api.movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviestatus', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MangaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangastatus', to='api.manga')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangastatus', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animestatus', to='api.anime')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animestatus', to='api.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='animes',
            field=models.ManyToManyField(through='api.AnimeStatus', to='api.Anime'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mangas',
            field=models.ManyToManyField(through='api.MangaStatus', to='api.Manga'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(through='api.MovieStatus', to='api.Movie'),
        ),
    ]
