# Generated by Django 3.2.9 on 2022-02-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220213_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
