# Generated by Django 3.2.9 on 2022-02-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterstatus', to='api.chapter')),
                ('mangastatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapterstatus', to='api.mangastatus')),
            ],
        ),
        migrations.AddField(
            model_name='mangastatus',
            name='chapters',
            field=models.ManyToManyField(through='api.ChapterStatus', to='api.Chapter'),
        ),
    ]
