# Generated by Django 3.2.9 on 2022-02-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220213_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('animestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonstatus', to='api.animestatus')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonstatus', to='api.season')),
            ],
        ),
    ]
