# Generated by Django 3.2.9 on 2022-02-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_seasonstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodestatus', to='api.episode')),
                ('seasonstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodestatus', to='api.seasonstatus')),
            ],
        ),
    ]
