# Generated by Django 3.2.9 on 2022-02-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_episodestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
    ]
